### ISSUE TITLE
Python 2.7 support; ImportError: No module named pathlib

### ISSUE THREAD

**Issue by jayvdb** [Sean1708/reFILE#1]
https://pypi.python.org/pypi/reFILE states it is Python 2 compatible

https://docs.python.org/3/library/pathlib.html is Python 3.4 only.

```
$ refile mv foo -m test
Traceback (most recent call last):
  File "/usr/bin/refile", line 7, in <module>
    from refile.cmdline import main
  File "/usr/lib/python2.7/site-packages/refile/cmdline.py", line 3, in <module>
    from . import engine
  File "/usr/lib/python2.7/site-packages/refile/engine.py", line 4, in <module>
    import pathlib
ImportError: No module named pathlib
```

There is a backport available:
https://pypi.python.org/pypi/pathlib2/

**Comment by jayvdb** [comment]
Hmm. strange.  A pathlib is being added as a dependency in 8b1c6ea39c11 .  It didnt work for me using pip. :/

**Comment by jayvdb** [comment]
Can reproduce this on Travis.
https://travis-ci.org/jayvdb/urllib3/jobs/86768391
https://travis-ci.org/jayvdb/urllib3/jobs/86768392
https://travis-ci.org/jayvdb/urllib3/jobs/86768394

**Comment by Sean1708** [comment]
Hmmm, very weird. I'll have a bit of a play with 2.7 over the weekend, see what I can figure out.

**Comment by Sean1708** [comment]
It might be that it needs `pathlib2` instead of `pathlib`.

**Comment by Sean1708** [comment]
Are you certain this isn't an error on your end? [All my builds work fine.](https://travis-ci.org/Sean1708/reFILE/builds/87298878)

**Comment by jayvdb** [comment]
The local builds are fine.  But builds of other projects that depends on this project that are failing.

The dependencies are not being included.

https://travis-ci.org/jayvdb/urllib3/jobs/86768391#L127

It is the wheel on pypi that is the problem.  Remove that and all is well, I believe.

Unzipping the wheel shows the `metadata.json` doesnt have `run_requires`, so I guess you built it using Python 3.4 as that doesnt have any dependencies.

I suspect that `universal = 1` from `setup.cfg` is part of the problem.
In order to be a universal wheel with environment specific dependencies, I believe setup.py needs to use environment markers as defined by PEP 426.  I havent distributed one of those beasts yet, so only know a little based on dabbling.

**Comment by Sean1708** [comment]
Right this should be working now, sorry for the wait.
